# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b168cc2628b6ed57af3d8ec8402a79044c36e32df15f8642d864b6862ed5776c43930c49412155aa0a557528c0944bb894448231f46c53dde37261d825c82356

test:
  secret_key_base: 03b283da476b858e3abf7047be30b1e8bc4a37a3b3928440664f6cbfa16bc8e840ce91d63d929a6ca73dc1d74d029d4d6b1d7d22e25c413fa52f1a5e1d098985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
